language: java
cache:
  directories:
    - "$HOME/.gradle"
jdk:
  - oraclejdk11
script:
  - "./gradlew clean test"
  - "./gradlew jacocoTestReport"
after_success:
  - bash <(curl -s https://codecov.io/bash)