format_version: 10
pipelines:
  File-DB:
    group: FileDB
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      JAVA_HOME: /gocd-jre
    materials:
      git-35d5024:
        git: https://github.com/juniorjainsahab/File-DB
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - test
                command: ./gradlew
                run_if: passed
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Build:
            timeout: 0
            artifacts:
            - build:
                source: build/libs/*
                destination: artifacts/file-db/libs
            tasks:
            - exec:
                arguments:
                - clean
                - build
                command: ./gradlew
                run_if: passed

